url: "https://ilselobker.com/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ilse LÃ¶bker" # the name of your site, e.g. ACME Corp.
